function changeen(){
    document.querySelector('.header__language-link_language_ru').style.textDecoration = "none";
    document.querySelector('.header__language-link_language_en').style.textDecoration = "underline";
    
    
    document.querySelector('.lead__title').style.opacity = 0;
    document.querySelector('.lead__subtitle').style.opacity = 0;
    document.querySelector('.lead__caption').style.opacity = 0;
    document.querySelector('.intro__title').style.opacity = 0;
    document.querySelector('.intro__text').style.opacity = 0;
    document.querySelector('#intro_list1').style.opacity = 0;
    document.querySelector('#intro_list2').style.opacity = 0;
    document.querySelector('#intro_list3').style.opacity = 0;
    document.querySelector('#intro_list4').style.opacity = 0;
    document.querySelector('#intro_list5').style.opacity = 0;
    document.querySelector('#place_title1').style.opacity = 0;
    document.querySelector('#place_title2').style.opacity = 0;
    document.querySelector('#place_title3').style.opacity = 0;
    document.querySelector('#place_title4').style.opacity = 0;
    document.querySelector('#place_title5').style.opacity = 0;
    document.querySelector('#place__paragraph1').style.opacity = 0;
    document.querySelector('#place__paragraph2').style.opacity = 0;
    document.querySelector('#place__paragraph3').style.opacity = 0;
    document.querySelector('#place__paragraph4').style.opacity = 0;
    document.querySelector('#place__paragraph5').style.opacity = 0;
    document.querySelector('#place__paragraph6').style.opacity = 0;
    document.querySelector('#place__paragraph7').style.opacity = 0;
    document.querySelector('#place__paragraph8').style.opacity = 0;
    document.querySelector('#place__paragraph9').style.opacity = 0;
    document.querySelector('.cover__title').style.opacity = 0;
    document.querySelector('.cover__subtitle').style.opacity = 0;
    document.querySelector('.payment__button').style.opacity = 0;
    document.querySelector('.loaction__title').style.opacity = 0;
    document.querySelector('#location_list1').style.opacity = 0;
    document.querySelector('#location_list2').style.opacity = 0;
    document.querySelector('#location_list3').style.opacity = 0;
    document.querySelector('#location_li1').style.opacity = 0;
    document.querySelector('#location_li2').style.opacity = 0;
    document.querySelector('#location_li3').style.opacity = 0;
    document.querySelector('#footer__link1').style.opacity = 0;
    document.querySelector('#footer__link2').style.opacity = 0;
    document.querySelector('#footer__link3').style.opacity = 0;
    document.querySelector('#footer__link4').style.opacity = 0;
    document.querySelector('#footer__link5').style.opacity = 0;
    document.querySelector('.footer__copyright').style.opacity = 0;


    document.querySelector('title').textContent = 'Travelling in Russia';
    document.querySelector('.lead__title').textContent = 'Travelling in Russia';
    document.querySelector('.lead__subtitle').textContent = 'The real country is not in the news, but here.';
    document.querySelector('.lead__caption').textContent = 'your shelf is on top';
    document.querySelector('.intro__title').textContent = 'What did we not see there?';
    document.querySelector('.intro__text').textContent = "According to WCIOM surveys, 95% of Russians dream of going somewhere, but only 36% plan to spend their vacations in their native country. Why haven't we seen anything here at home?  Actually, Russia is a whole universe with a tender sea of the south, thick forests of the Sayans and severe ice of the Putorana Plateau. And you can also see all these beauties without millions on account, foreign passports and many hours of flight. For example, Vera Bashmakova, a brave young mother who took three children into her arms, put them in her 'Lada' and drove 20 thousand kilometers through her native country. We chose and described some interesting places worthy of your vacation.";
    document.querySelector('#intro_list1').textContent = 'Time zones';
    document.querySelector('#intro_list2').textContent = 'UNESCO natural heritage sites';
    document.querySelector('#intro_list3').textContent = 'UNESCO cultural heritage sites';
    document.querySelector('#intro_list4').textContent = 'Natural Reserves';
    document.querySelector('#intro_list5').textContent = 'Airports';
    document.querySelector('#place_title1').textContent = 'Curonian Spit';
    document.querySelector('#place_title2').textContent = 'Kolsky';
    document.querySelector('#place_title3').textContent = 'Altay';
    document.querySelector('#place_title4').textContent = 'Winter Lake Baikal';
    document.querySelector('#place_title5').textContent = 'Karelia';
    document.querySelector('#place__paragraph1').textContent = 'Here, in the middle of forests and sand dunes, you can see two water horizons - the calm Curonian Gulf on one side and the rippled Baltic Sea waves on the other. This is a unique natural zone on the edge of the Russian enclave.';
    document.querySelector('#place__paragraph2').textContent = "The Kaliningrad region does not end there. For a traveler and researcher there in the neighborhood - the westernmost point of Russia, the Baltic Spit - and the German heritage of the placer of small seaside towns. The atmosphere of these places excludes fuss, plunging into nature's calmness and the smell of steel, cool sea.";
    document.querySelector('#place__paragraph3').textContent = 'Almost the entire peninsula is located above the Arctic Circle. The Saami tundra, from which the taiga is to the south and the Arctic Ocean is to the north, pretending to be the Barents Sea.';
    document.querySelector('#place__paragraph4').textContent = "You may have watched Zvyagintsev and even heard the history of the Arctic Festival in Teriberka. Perhaps the word «Khibiny» is not left under the snow of school memories of geography lessons. Perhaps you weren't interested in the super-deep hole that penetrates the earth's crust, and apatite has long been a cause of apathy. But your dream of seeing the northern lights begins to come true with a ticket to Murmansk.";
    document.querySelector('#place__paragraph5').textContent = "Altai is one of the most beautiful places in Russia. First of all because of the mountains: if you drive along the ridge, you will see slopes covered with pine trees, mountain rivers and lakes. And if you open the windows in the car, you can get acquainted with the invisible wonder of local places - mountain air.";
    document.querySelector('#place__paragraph6').textContent = "The climate in the Altai is temperate, so it is best to go here in the summer. So you will see the diversity of local flora and fauna. Elks roam the forests of the Altai, eagles fly over the ridges, and on the plains roes graze. And the famous Pallas trees are also the inhabitants of the Altai region.";
    document.querySelector('#place__paragraph7').textContent = "Everyone knows Baikal as the largest lake in the world. Many also know that it is the largest source of fresh water and one of the most beautiful places in Russia.";
    document.querySelector('#place__paragraph8').textContent = "Of course, it is all true. But Baikal is still an ideal place for skijoring competitions. It is such a sport when a skier ties himself to a motorcycle and tandem tries to develop as much speed as possible on ice. In March 2019 at the festival «Baikal Mile» was set a world record - 197.011 km/h.";
    document.querySelector('#place__paragraph9').textContent = "Siberia ends not in the Urals, but in Karelia: the Siberian larch that forms the taiga does not grow west of Vodlozer. But here it swings for 30 meters - forests of Karelian national parks because of impassable swamps have never known an axe. Some pines are more than half a millennium old. Touch a living creature that saw the sun before Ivan the Terrible saw it. In a virgin forest for a hundred kilometers you will not find a path. And on rare paths, trees a couple of meters from the ground are marked with bear claws. So that everyone knows who the owner is.";
    document.querySelector('.cover__title').textContent = "To Baikal «on dogs»";
    document.querySelector('.cover__subtitle').textContent = "Based on the training theme about Transsib and iframes - a trip from the capital to Baikal by train.";
    document.querySelector('.payment__button').textContent = 'GO!';
    document.querySelector('.loaction__title').textContent = 'Our offices';
    document.querySelector('#location_list1').textContent = 'Addresses:';
    document.querySelector('#location_li1').textContent = 'Yubileynaya 6A, Dzerzhinskiy 121, Khrutskaya 5';
    document.querySelector('#location_list2').textContent = 'office contact numbers:';
    document.querySelector('#location_li2').textContent = '+80296954113, +80333642795, +80446789355';
    document.querySelector('#location_list3').textContent = 'Working hours:';
    document.querySelector('#footer__link1').textContent = 'Maps';
    document.querySelector('#footer__link2').textContent = 'Weather';
    document.querySelector('#footer__link3').textContent = 'Timetable';
    document.querySelector('#footer__link4').textContent = 'Calendar';
    document.querySelector('#footer__link5').textContent = 'Travels';
    document.querySelector('.footer__copyright').textContent = '© 2020. Papkov Andrey +88005553535';
    
    


    
    $('.lead__title').animate({opacity: 1}, 'slow');
    $('.lead__subtitle').animate({opacity: 1}, 'slow');
    $('.lead__caption').animate({opacity: 1}, 'slow');
    $('.intro__title').animate({opacity: 1}, 'slow');
    $('.intro__text').animate({opacity: 1}, 'slow');
    $('#intro_list1').animate({opacity: 1}, 'slow');
    $('#intro_list2').animate({opacity: 1}, 'slow');
    $('#intro_list3').animate({opacity: 1}, 'slow');
    $('#intro_list4').animate({opacity: 1}, 'slow');
    $('#intro_list5').animate({opacity: 1}, 'slow');
    $('#place_title1').animate({opacity: 1}, 'slow');
    $('#place_title2').animate({opacity: 1}, 'slow');
    $('#place_title3').animate({opacity: 1}, 'slow');
    $('#place_title4').animate({opacity: 1}, 'slow');
    $('#place_title5').animate({opacity: 1}, 'slow');
    $('#place__paragraph1').animate({opacity: 1}, 'slow');
    $('#place__paragraph2').animate({opacity: 1}, 'slow');
    $('#place__paragraph3').animate({opacity: 1}, 'slow');
    $('#place__paragraph4').animate({opacity: 1}, 'slow');
    $('#place__paragraph5').animate({opacity: 1}, 'slow');
    $('#place__paragraph6').animate({opacity: 1}, 'slow');
    $('#place__paragraph7').animate({opacity: 1}, 'slow');
    $('#place__paragraph8').animate({opacity: 1}, 'slow');
    $('#place__paragraph9').animate({opacity: 1}, 'slow');
    $('.cover__title').animate({opacity: 1}, 'slow');
    $('.cover__subtitle').animate({opacity: 1}, 'slow');
    $('.payment__button').animate({opacity: 1}, 'slow');
    $('.loaction__title').animate({opacity: 1}, 'slow');
    $('#location_list1').animate({opacity: 1}, 'slow');
    $('#location_list2').animate({opacity: 1}, 'slow');
    $('#location_list3').animate({opacity: 1}, 'slow');
    $('#location_li1').animate({opacity: 1}, 'slow');
    $('#location_li2').animate({opacity: 1}, 'slow');
    $('#location_li3').animate({opacity: 1}, 'slow');
    $('#footer__link1').animate({opacity: 1}, 'slow');
    $('#footer__link2').animate({opacity: 1}, 'slow');
    $('#footer__link3').animate({opacity: 1}, 'slow');
    $('#footer__link4').animate({opacity: 1}, 'slow');
    $('#footer__link5').animate({opacity: 1}, 'slow');
    $('.footer__copyright').animate({opacity: 1}, 'slow');


};    
function changeru(){
    document.querySelector('.header__language-link_language_en').style.textDecoration = "none";
    document.querySelector('.header__language-link_language_ru').style.textDecoration = "underline";
    
    
    document.querySelector('.lead__title').style.opacity = 0;
    document.querySelector('.lead__subtitle').style.opacity = 0;
    document.querySelector('.lead__caption').style.opacity = 0;
    document.querySelector('.intro__title').style.opacity = 0;
    document.querySelector('.intro__text').style.opacity = 0;
    document.querySelector('#intro_list1').style.opacity = 0;
    document.querySelector('#intro_list2').style.opacity = 0;
    document.querySelector('#intro_list3').style.opacity = 0;
    document.querySelector('#intro_list4').style.opacity = 0;
    document.querySelector('#intro_list5').style.opacity = 0;
    document.querySelector('#place_title1').style.opacity = 0;
    document.querySelector('#place_title2').style.opacity = 0;
    document.querySelector('#place_title3').style.opacity = 0;
    document.querySelector('#place_title4').style.opacity = 0;
    document.querySelector('#place_title5').style.opacity = 0;
    document.querySelector('#place__paragraph1').style.opacity = 0;
    document.querySelector('#place__paragraph2').style.opacity = 0;
    document.querySelector('#place__paragraph3').style.opacity = 0;
    document.querySelector('#place__paragraph4').style.opacity = 0;
    document.querySelector('#place__paragraph5').style.opacity = 0;
    document.querySelector('#place__paragraph6').style.opacity = 0;
    document.querySelector('#place__paragraph7').style.opacity = 0;
    document.querySelector('#place__paragraph8').style.opacity = 0;
    document.querySelector('#place__paragraph9').style.opacity = 0;
    document.querySelector('.cover__title').style.opacity = 0;
    document.querySelector('.cover__subtitle').style.opacity = 0;
    document.querySelector('.payment__button').style.opacity = 0;
    document.querySelector('.loaction__title').style.opacity = 0;
    document.querySelector('#location_list1').style.opacity = 0;
    document.querySelector('#location_list2').style.opacity = 0;
    document.querySelector('#location_list3').style.opacity = 0;
    document.querySelector('#location_li1').style.opacity = 0;
    document.querySelector('#location_li2').style.opacity = 0;
    document.querySelector('#location_li3').style.opacity = 0;
    document.querySelector('#footer__link1').style.opacity = 0;
    document.querySelector('#footer__link2').style.opacity = 0;
    document.querySelector('#footer__link3').style.opacity = 0;
    document.querySelector('#footer__link4').style.opacity = 0;
    document.querySelector('#footer__link5').style.opacity = 0;
    document.querySelector('.footer__copyright').style.opacity = 0;


    document.querySelector('title').textContent = 'Путешествия по России';
    document.querySelector('.lead__title').textContent = 'Путешествия по России';
    document.querySelector('.lead__subtitle').textContent = 'Настоящая страна не в выпусках новостей, а здесь.';
    document.querySelector('.lead__caption').textContent = 'ВАША ПОЛКА — ВЕРХНЯЯ';
    document.querySelector('.intro__title').textContent = 'Чего мы там не видели?';
    document.querySelector('.intro__text').textContent = "По опросам ВЦИОМ, 95% россиян мечтают куда-нибудь поехать, но только 36% планируют провести отпуск в родной стране. Мол, чего мы тут, дома, не видели? На самом деле, Россия — это целая вселенная с ласковым морем юга, густыми лесами Саян и суровыми льдами плато Путорана. А ещё увидеть все эти красоты можно без миллионов на счету, загранпаспорта и многочасовых перелетов. Как, например, Вера Башмакова — смелая молодая мама, которая взяла в охапку троих детей, усадила их в свою «Ладу» и проехала 20 тысяч километров по родной стране. Мы выбрали и описали некоторые интересные места, достойные вашего отпуска.";
    document.querySelector('#intro_list1').textContent = 'Часовых поясов';
    document.querySelector('#intro_list2').textContent = 'Объектов природного наследия ЮНЕСКО';
    document.querySelector('#intro_list3').textContent = 'Объектов культурного наследия ЮНЕСКО';
    document.querySelector('#intro_list4').textContent = 'Природных заповедников';
    document.querySelector('#intro_list5').textContent = 'Аэропортов';
    document.querySelector('#place_title1').textContent = 'Куршская коса';
    document.querySelector('#place_title2').textContent = 'Кольский';
    document.querySelector('#place_title3').textContent = 'Алтай';
    document.querySelector('#place_title4').textContent = 'Зимний Байкал';
    document.querySelector('#place_title5').textContent = 'Карелия';
    document.querySelector('#place__paragraph1').textContent = 'Здесь, посреди лесов и песчаных дюн, вы сможете увидеть два водных горизонта — спокойного Куршского залива с одной стороны и подёрнутого рябью волн Балтийского моря с другой. Уникальная природная зона на краю российского анклава.';
    document.querySelector('#place__paragraph2').textContent = 'На этом Калининградская область не заканчивается. Для путешественника и исследователя там же по соседству — самая западная точка России, Балтийская коса, — и немецкое наследие россыпи небольших приморских городов. Атмосфера здешних мест исключает суету, окуная в спокойствие природы и запах стального, прохладного моря.';
    document.querySelector('#place__paragraph3').textContent = 'Почти весь полуостров находится за Полярным кругом. Саамская тундра, от которой на юг — тайга, а на север — Ледовитый океан, прикидывающийся Баренцевым морем.';
    document.querySelector('#place__paragraph4').textContent = 'Возможно, вы смотрели Звягинцева и даже слышали историю арктического фестиваля в Териберке. Возможно, слово «Хибины» не осталось под снегом школьных воспоминаний об уроках географии. Возможно, вы не интересовались пронизывающей земную кору сверхглубокой скважиной, а от апатитов вас давно накрывает апатия. Но ваша мечта увидеть северное сияние начинает сбываться с билетом в Мурманск.';
    document.querySelector('#place__paragraph5').textContent = 'Алтай — одно из красивейших мест в России. В первую очередь из-за гор: если ехать вдоль хребта, вы увидите склоны, усыпанные соснами, горные реки и озёра. А если вы откроете в автомобиле окна, сможете познакомиться с невидимым чудом здешних мест — горным воздухом.';
    document.querySelector('#place__paragraph6').textContent = 'Климат на Алтае умеренный, поэтому ехать сюда лучше всего летом. Так вы увидите всё разнообразие местной флоры и фауны. По лесам Алтая бродят лоси, над хребтами летают орлы, а на равнинах пасутся косули. И знаменитые манулы — тоже обитатели Алтайского края.';
    document.querySelector('#place__paragraph7').textContent = 'Всем известен Байкал как крупнейшее озеро в мире. Многие также знают, что это самый большой источник пресной воды и одно из красивейших мест в России.';
    document.querySelector('#place__paragraph8').textContent = 'Конечно, это всё так. Но Байкал ещё идеальное место для соревнований по скийорингу. Это такой вид спорта, когда лыжник привязывает себя к мотоциклу, и тандем старается развить как можно бóльшую скорость на льду. В марте 2019 года на фестивале «Байкальская миля» был поставлен мировой рекорд — 197.011 км/ч.';
    document.querySelector('#place__paragraph9').textContent = 'Сибирь заканчивается не на Урале, а в Карелии: образующая тайгу сибирская лиственница не растёт западнее Водлозера. Зато здесь она вымахивает на 30 метров — леса карельских национальных парков из-за непроходимых болот никогда не знали топора. Некоторым соснам уже больше чем полтысячелетия. Прикоснитесь к живому существу, видевшему солнце раньше, чем увидал его Иван Грозный. В девственном лесу на сотню километров не встретишь тропы. А на редких тропинках деревья в паре метров от земли помечены медвежьими когтями. Чтобы все знали, кто тут хозяин.';
    document.querySelector('.cover__title').textContent = "До Байкала «на собаках»";
    document.querySelector('.cover__subtitle').textContent = "По мотивам учебной темы о Транссибе и iframes — путешествие от столицы до Байкала на электричках.";
    document.querySelector('.payment__button').textContent = 'Вперед!';
    document.querySelector('.loaction__title').textContent = 'Наши офисы';
    document.querySelector('#location_list1').textContent = 'Адреса:';
    document.querySelector('#location_li1').textContent = 'Юбилейная 6А, Дзержинского 121, Хруцкая 5';
    document.querySelector('#location_list2').textContent = 'контакные номера офисов:';
    document.querySelector('#location_li2').textContent = '+80296954113, +80333642795, +80446789355';
    document.querySelector('#location_list3').textContent = 'График работы:';
    document.querySelector('#footer__link1').textContent = 'Карты';
    document.querySelector('#footer__link2').textContent = 'Погода';
    document.querySelector('#footer__link3').textContent = 'Расписание';
    document.querySelector('#footer__link4').textContent = 'Календарь';
    document.querySelector('#footer__link5').textContent = 'Путешествия';
    document.querySelector('.footer__copyright').textContent = '© 2020. Папков Андрей +88005553535';
    
    


    
    $('.lead__title').animate({opacity: 1}, 'slow');
    $('.lead__subtitle').animate({opacity: 1}, 'slow');
    $('.lead__caption').animate({opacity: 1}, 'slow');
    $('.intro__title').animate({opacity: 1}, 'slow');
    $('.intro__text').animate({opacity: 1}, 'slow');
    $('#intro_list1').animate({opacity: 1}, 'slow');
    $('#intro_list2').animate({opacity: 1}, 'slow');
    $('#intro_list3').animate({opacity: 1}, 'slow');
    $('#intro_list4').animate({opacity: 1}, 'slow');
    $('#intro_list5').animate({opacity: 1}, 'slow');
    $('#place_title1').animate({opacity: 1}, 'slow');
    $('#place_title2').animate({opacity: 1}, 'slow');
    $('#place_title3').animate({opacity: 1}, 'slow');
    $('#place_title4').animate({opacity: 1}, 'slow');
    $('#place_title5').animate({opacity: 1}, 'slow');
    $('#place__paragraph1').animate({opacity: 1}, 'slow');
    $('#place__paragraph2').animate({opacity: 1}, 'slow');
    $('#place__paragraph3').animate({opacity: 1}, 'slow');
    $('#place__paragraph4').animate({opacity: 1}, 'slow');
    $('#place__paragraph5').animate({opacity: 1}, 'slow');
    $('#place__paragraph6').animate({opacity: 1}, 'slow');
    $('#place__paragraph7').animate({opacity: 1}, 'slow');
    $('#place__paragraph8').animate({opacity: 1}, 'slow');
    $('#place__paragraph9').animate({opacity: 1}, 'slow');
    $('.cover__title').animate({opacity: 1}, 'slow');
    $('.cover__subtitle').animate({opacity: 1}, 'slow');
    $('.payment__button').animate({opacity: 1}, 'slow');
    $('.loaction__title').animate({opacity: 1}, 'slow');
    $('#location_list1').animate({opacity: 1}, 'slow');
    $('#location_list2').animate({opacity: 1}, 'slow');
    $('#location_list3').animate({opacity: 1}, 'slow');
    $('#location_li1').animate({opacity: 1}, 'slow');
    $('#location_li2').animate({opacity: 1}, 'slow');
    $('#location_li3').animate({opacity: 1}, 'slow');
    $('#footer__link1').animate({opacity: 1}, 'slow');
    $('#footer__link2').animate({opacity: 1}, 'slow');
    $('#footer__link3').animate({opacity: 1}, 'slow');
    $('#footer__link4').animate({opacity: 1}, 'slow');
    $('#footer__link5').animate({opacity: 1}, 'slow');
    $('.footer__copyright').animate({opacity: 1}, 'slow');


};    